- hosts: all
  tasks:
  - name: install apache
    package:
      name: "{{ package }}"
      state: latest
  - name: ensure httpd is running
    service:
      name: "{{ package }}"
      state: started
      enabled: true
